---
title: Atelier du réseau sondage
subtitle: Estimation de la variance par approche analytique - application avec **gustave**
format: 
    clean-revealjs:
        transition: slide
        smaller: true
        preview-links: true
        width: 1500
        margin: 0.05
        toc: false
        vertical: false
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Khaled Larbi
    email: prenom point nom arobase insee point fr
    affiliations: Insee
date: last-modified
---

# Pourquoi estimer la variance d'un estimateur ? 

# Estimation de variance simple
## Définitions usuelles et notations. 

Dans cette présentation, on notera :

- $\mathcal{U}$, une population finie de taille $N$,
- $p$, un plan de sondage défini sur $\mathcal{U}$,
- $S$ un échantillon aléatoire tiré selon le plan $p$.


- $\{y_k\}$ : une variable d'intérêt,
- $\{x_k\}$ : une variable auxiliaire. 

Pour l'inférence, il est commode d'introduire : 

- pour tout individu $k \in \mathcal{U}, ~ \pi_k = \mathbb{P}(k \in S)$ $\to$ probabilité d'inclusion d'ordre 1.
  - il s'agit de la probabilité que l'individu $k$ soit dans l'échantillon $S$.
- pour tout couple d'individus $(k,l) \in \mathcal{U}^2, ~ \pi_{kl} = \mathbb{P}(k \in S \cap l \in S)$ $\to$ probabilité d'inclusion d'ordre 2.
  - il s'agit de la probabilité que les individus $k$ et $l$ soient conjointement dans l'échantillon $S$



## Estimateur d'Horvitz-Thompson

- Comment estimer le total $t_y = \sum_{k \in \mathcal{U}} y_k$ en utilisant l'information disponible uniquement sur l'échantillon $S$ ?

::: {#def-estHT}
## Estimateur d'Horvitz-Thompson
L'estimateur $\hat{t}_{y,\text{HT}} = \sum_{k \in S} \frac{y_k}{\pi_k}$ est appelé estimateur d'Hovitz-Thompson du total. 
:::

- Est-ce un *bon* estimateur ? 
  - Critère de biais et de variance.  
- 



:::: {.columns}

::: {.column width="50%"}
::: {.callout-caution icon="false"}
::: {#def-biais}
## Biais d'un estimation
Le biais d'un estimateur $\hat \theta$ d'une fonction d'intérêt $\theta$ est donné par $\mathbb{B}(\hat \theta; \theta) = \mathbb{E}(\hat \theta) - \theta$. 
:::
:::
:::

::: {.column width="50%"}
::: {.callout-caution icon="false"}
::: {#def-var}
## Variance
La variance d'un estimateur $\hat \theta$ d'une fonction d'intérêt $\theta$ est donné par $\mathbb{V}(\hat \theta) = \mathbb{E}(\left(\hat \theta  - \mathbb{E}(\hat \theta) \right)^2)$. 

La variance permet de quantifier la variabilité d'un estimateur.
:::
:::
:::

::::


## Arbitrage biais/variance


## Estimateur d'Horvitz-Thompson : biais et variance

- Si pour tout $k \in \mathcal{U},~~ \pi_k > 0$ alors $\hat{t}_{y,\text{HT}}$ est un estimateur sans biais de $t_y$.

- Si il existe un individu $j$ tel que $\pi_j = 0$, alors il y a un défaut de couverture $\to$ biais. 

- Quid de la variance de $\hat{t}_{y,\text{HT}}$ ?
  - $$\mathbb{V}(\hat t_{y,\text{HT}}) = \sum_{k \in \color{red}{\mathcal{U}}} \sum_{l \in \color{red}{\mathcal{U}}} \frac{y_k}{\pi_k} \frac{y_l}{\pi_l} \Delta_{kl}$$ où $\Delta_{kl} = \pi_{kl} - \pi_k \pi_l$
  - Problème : la variance est fonction des valeurs de $\{y_k\}$ sur $\color{red}{\mathcal{U}}$ mais cette information n'est disponible que sur $\mathcal{S}$
  - Solution : estimer la variance.


:::: {.columns}

::: {.column width="50%"}
::: {.callout-caution icon="false"}
## Estimateur de variance d'Horvitz-Thompson
 $$\hat{\mathbb{V}}_\text{HT}(\hat t_{y,\text{HT}}) = \sum_{k \in \mathcal{U}} \sum_{k \in \mathcal{U}} \frac{y_k}{\pi_k} \frac{y_l}{\pi_l} \Delta_{kl} \color{red}{\frac{I_{kl}}{\pi_{kl}}} \color{black} = \sum_{k \in S} \sum_{l \in S} \frac{y_k}{\pi_k} \frac{y_l}{\pi_l} {\frac{\Delta_{kl}}{\pi_{kl}}} $$ 

 Propriétés : 

 - Si pour tout $(k,l) \in \mathcal{U}^2$, $\pi_{kl} > 0$, $\hat{\mathbb{V}}_\text{HT}(\hat t_{y,\text{HT}})$ est sans biais pour $\mathbb{V}_\text{HT}(\hat t_{y,\text{HT}})$
:::
:::

::: {.column width="50%"}
::: {.callout-caution icon="false"}
## Estimateur de Sen-Yates-Grundy
$$\hat{\mathbb{V}}_\text{SYG}(\hat t_{y,\text{HT}}) =  - \frac{1}{2} \sum_{k \in \mathcal{S}} \sum_{l \in \mathcal{S} | k \neq l} \left(\frac{y_k}{\pi_k} - \frac{y_l}{\pi_l} \right)^2 \frac{\Delta_{kl}}{\pi_{kl}}$$

 Propriétés : 
 
 - Si pour tout $(k,l) \in \mathcal{U}^2$, $\pi_{kl} > 0$ et le plan $p$ est de taille fixe alors $\hat{\mathbb{V}}_\text{SYG}(\hat t_{y,\text{HT}})$ est sans biais pour $\mathbb{V}_\text{HT}(\hat t_{y,\text{HT}})$.
- Si pour tout $(k,l) \in \mathcal{U}^2$, $\pi_{kl} - \pi_k \pi_l \leq 0$ alors $\hat{\mathbb{V}}_\text{SYG}(\hat t_{y,\text{HT}}) \geq 0$.
:::
:::
::::


# Application à quelques plans de sondage.

::: {.callout-caution icon="false"}
## Plan aléatoire simple sans remise 

:::


::: {.callout-caution icon="false"}
## Plan poissonien

:::

::: {.callout-caution icon="false"}
## Plan de l'enquête Histoire de Vie et Patrimoine 

- Calcul des probabilités d'inclusion ? 

:::
